#!/bin/bash
jq -r '
  . as $poke |
  "\(.name) is of type \(.types[0].type.name), weighs \(.weight)kg, and is \(.height)m tall."
' pikachu.json | sed -E 's/(^| )([a-z])/\1\u\2/g' | awk '{printf "%s\n", $0}'